### ISSUE TITLE
Resources dir missing from WAR File

### ISSUE THREAD

**Issue by espeed** [pedestal/docs#20]
The "Deploying a WAR File" docs don't include steps for including the resources directory in the WAR:

http://pedestal.io/documentation/service-war-deployment/

This pull request adds resources/* to the copy command:
https://github.com/pedestal/docs/pull/19

**Comment by ohpauleez** [comment]
This was updated in the [repo docs](https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-war-deployment.md)
