### ISSUE TITLE
is the doc updated?..error with (tools-help)

### ISSUE THREAD

**Issue by cocodrino** [pedestal/docs#22]
Hi..I'm not sure, but I'm following this documentation, first point: the project.clj is a bit different now, I've preferred dont do changes in this file and keep exactly as the generated by lein new pedestal-service

2) I run my repl but when I try
(tools-help) 

I get 

CompilerException java.lang.RuntimeException: Unable to resolve symbol: tools-help in this context, compiling:(/tmp/form-init7413359724321465815.clj:1:1) 

then I try
(use 'io.pedestal.service-tools.dev)

but again I get the same error

and checking the namespace
https://github.com/pedestal/pedestal/blob/master/service-tools/src/io/pedestal/service_tools/dev.clj

I notice than now it's a bit different...and I'm confused...

how is the correct way of start the server (and restart) using repl?

(start) (run-dev) (server/start runnable-service)

ehh..notice than I'm not a clojure expert, I'm a bit newbie so, probably it results obvious to clojure experts but for me is a bit confusing..thank so much

**Comment by ohpauleez** [comment]
Hi - As per the README within the Pedestal Repo, the documentation actually lives at: https://github.com/pedestal/pedestal/tree/master/guides/documentation
For your question, you should see the answer here: https://groups.google.com/d/msg/pedestal-users/Lma1UP5yvtM/Rki333wLPQAJ
