### ISSUE TITLE
Deprecate docs to point people to main Pedestal docs

### ISSUE THREAD

**Issue by danielcompton** [pedestal/docs#23]
It might be good to point people to [pedestal/pedestal](https://github.com/pedestal/pedestal/tree/master/guides/documentation for documentation), as it looks like this repo isn't the source of documentation anymore?

**Comment by ohpauleez** [comment]
Done.  Thanks!

**Comment by rauhs** [comment]
Googleing "pedestal interceptor" will still end up on the old docs as the first hit. Should the docs be `docs/` directory be removed, or maybe all docs edited with a  link to the new docs?
