### ISSUE TITLE
`Service Routing` link is broken

### ISSUE THREAD

**Issue by kumarshantanu** [pedestal/docs#24]
See the section here:
https://github.com/pedestal/docs/blob/master/documentation/service-interceptors.md#porting-ring-code

The _Service Routing_ link is leading to 404.

**Comment by ohpauleez** [comment]
This repo is old.  Please use the docs that are part of the main Pedestal repo: https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-interceptors.md
